In [30]:
import numpy as np

coordinates = [[551, 465], [485, 428], [702, 188]]

np_coordinates = np.array(coordinates)
wrist_coordinates = np_coordinates[0]

relative_coordinates = np_coordinates - wrist_coordinates
relative_coordinates

array([[   0,    0],
       [ -66,  -37],
       [ 151, -277]])

In [31]:
# flatten
flattened_coordinates = relative_coordinates.flatten()
flattened_coordinates

array([   0,    0,  -66,  -37,  151, -277])

In [34]:
# normalize

max_value = np.abs(flattened_coordinates).max()

normalized = flattened_coordinates/max_value
normalized.reshape(1, -1).shape

(1, 6)

In [18]:
print(*normalized)

0.0 0.0 -0.23826714801444043 -0.13357400722021662 0.5451263537906137 -1.0


In [68]:
import pandas as pd


data = pd.read_csv('data/keypoint.csv', header=None)
print(len(data))
print(data[0].value_counts())

4384


5    588
2    579
1    565
0    549
7    546
3    542
6    511
4    504
Name: 0, dtype: int64

8

In [38]:
test = data.sample(1)
y, x = test.values[:, 0], test.values[:, 1:]
y, x

(array([1.]),
 array([[ 0.        ,  0.        ,  0.0741573 , -0.15505618,  0.0988764 ,
         -0.37752809,  0.11011236, -0.54606742,  0.13483146, -0.67191011,
         -0.03595506, -0.57078652, -0.08089888, -0.75505618, -0.11460674,
         -0.86292135, -0.14831461, -0.96629213, -0.08764045, -0.53707865,
         -0.13932584, -0.74606742, -0.1752809 , -0.87865169, -0.21123596,
         -1.        , -0.1258427 , -0.46292135, -0.17977528, -0.65617978,
         -0.20898876, -0.78202247, -0.24269663, -0.90337079, -0.15730337,
         -0.35505618, -0.20674157, -0.49213483, -0.23820225, -0.58876404,
         -0.26741573, -0.68764045]]))

In [39]:
from model_architecture import model
import torch

model.load_state_dict(torch.load('model.pth'))
model.eval
with torch.no_grad():
    print(torch.argmax(model(torch.tensor(x, dtype=torch.float)), dim=1).item())

1


'Play'